[package]
name = "lazynmap"
version = "0.1.0"
edition = "2024"
authors = ["Rui Jiang me@ruijiang.me"]
license = "MIT"
description = "A TUI for interactively generating nmap commands"
readme = "README.md"
repository = "https://github.com/ruiiiijiiiiang/lazynmap"
keywords = ["cybersecurity", "nmap", "scanner", "reconnaissance"]
categories = ["command-line-utilities", "security"]
exclude = ["./assets"]

[dependencies]
arboard = "3.6.1"
clap = { version = "4.5.51", features = ["derive"] }
color-eyre = "0.6.0"
once_cell = "1.21.3"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
strum = "0.27.0"
strum_macros = "0.27.0"
