[package]
name = "lazynmap"
version = "0.1.3"
edition = "2024"
authors = ["Rui Jiang me@ruijiang.me"]
license = "MIT"
description = "A TUI for interactively generating nmap commands"
readme = "README.md"
repository = "https://github.com/ruiiiijiiiiang/lazynmap"
keywords = ["cybersecurity", "nmap", "scanner", "reconnaissance"]
categories = ["command-line-utilities", "security"]
exclude = ["./assets"]

[dependencies]
arboard = "3.6"
clap = { version = "4.6", features = ["derive"] }
color-eyre = "0.6"
once_cell = "1.21"
ratatui = { version = "0.30", features = ["all-widgets"] }
strum = "0.28"
strum_macros = "0.28"
